import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-gray-900 text-white p-4">
          <ul className="flex space-x-6">
            <li><Link href="/products">Productos</Link></li>
            <li><Link href="/services">Servicios</Link></li>
            <li><Link href="/team">Equipo</Link></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
